repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-executables-have-shebangs
    -   id: check-shebang-scripts-are-executable
    -   id: fix-encoding-pragma
        args: [ '--remove' ]
    -   id: name-tests-test
        args: [ '--django' ]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        additional_dependencies:
            - sqlalchemy-stubs
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
        language_version: python3
